### ISSUE TITLE
Artifact name should be the commit hash

### ISSUE THREAD

**Issue by cpoczatek** [oracle-quickstart/oci-quickstart#10]
Since the artifact name is only visible to the publisher and is a copy of the assets in the repo that the action is post-ing it's name should be the shortened commit hash to make it obvious how the artifact maps to the repo.

**Comment by lucassrg** [comment]
Artifact Name is also visible to the consumer in case of an Image artifact - that's the Image Name on Compute page.
One solution could be to follow the same name standard Compute uses to name platform images for the Artifact, and use Release feature of GitHub to associate that Artifact name with the commit tag.
