### ISSUE TITLE
use clean action for update-listing

### ISSUE THREAD

**Issue by benofben** [oracle-quickstart/oci-quickstart#24]
Use dockerfile and entrypoint.sh from here:
https://github.com/oracle-quickstart/oci-quickstart/tree/dev_ben_lackey/actions/update-listing

Scope action down to just update a stack (not handle images, not create new)

Use . instead of /

Refactor python to be a single file and drop unused functionality.  Drop comment block and start of code.  Move main entry point to a main function.  Refactor global variables as local.  Ensure json is handled natively, not as strings.  Simplify variable and function names to ensure readability.

**Comment by dbcopas** [comment]
please split this into separate issues. some of these are by design
