### ISSUE TITLE
peg tf to latest

### ISSUE THREAD

**Issue by benofben** [oracle-quickstart/oci-quickstart#5]

**Comment by benofben** [comment]
Moved to latest (24), I'm not sure how to grab it automatically.

**Comment by cpoczatek** [comment]
Just [wild](https://github.com/hashicorp/terraform/issues/9803)...

Wrong OS but
`echo "https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')_darwin_amd64.zip"`

**Comment by dbcopas** [comment]
this was resolved
